# -*- coding: utf-8 -*-
"""Welcome To Colab 


Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd
# --CREDIT IRFAN PATEL

# Upload your dataset
df = pd.read_csv('exp1_bmi.csv')

# Show first 5 rows
print("First 5 rows of dataset:")
print(df.head())

# Descriptive Stats for numeric columns
print("\n--- Descriptive Statistics (Numeric Columns) ---")
print(df.describe())

# Mean
print("\nMean:")
print(df.mean(numeric_only=True))

# Median
print("\nMedian:")
print(df.median(numeric_only=True))

# Mode
print("\nMode:")
print(df['Height'].mode()[0])

# Standard Deviation
print("\nStandard Deviation:")
print(df.std(numeric_only=True))

# Min & Max
print("\nMinimum Values:")
print(df.min(numeric_only=True))
print("\nMaximum Values:")
print(df.max(numeric_only=True))

# Count of non-null values per column
print("\nCount (Non-null values in each column):")
print(df.count())

# Percentiles
print("\n Quartiles and InterQuartile Range:  ")


q1 = df['Height'].quantile(0.25)
q3 = df['Height'].quantile(0.75)

IQR = q3-q1

print(q3,q1,IQR)

